steps:
  - name: 'gcr.io/cloud-builders/kubectl'
    id: Set Env & Secrets
    entrypoint: bash
    args:
    - '-e'
    - '-c'
    - |
     gcloud container clusters get-credentials teste-implementacao-haytek --region us-central1 --project haytek-ondemand
     git clone https://github.com/cog-bruno-faustino/airbyte.git --depth=3
     cd airbyte
     kubectl apply -k kube/overlays/stable
     kubectl get pods
